openHPI/xikolo-ios

xikolo-common/Data/Helper/NetworkHelper.swift, xikolo-ios/CourseContentTableViewController.swift, xikolo-ios/DashboardViewController.swift, xikolo-ios/NewsViewController.swift, xikolo-ios/QuizWebViewController.swift, xikolo-ios/VideoViewController.swift
added video and quiz detail view, quiz view works with api v1, video view has a mock url
=> Video and Quiz detail views for iOS

xikolo-ios/Base.lproj/TabCourses.storyboard, xikolo-ios/Base.lproj/TabDashboard.storyboard, xikolo-ios/Base.lproj/TabProfile.storyboard, xikolo-ios/TabNews.storyboard
which sadly means confusing storyboards, since the content now hides behind the navigationsBars, but it's fine when the app is running.
=> Solved "white header problem" in all custom views

xikolo-common/Data/Helper/NewsArticleHelper.swift, xikolo-common/Data/Model/NewsArticle+CoreDataProperties.swift, xikolo-common/Data/Model/NewsArticle.swift, xikolo-common/Data/Provider/NewsArticleProvider.swift, xikolo-common/Data/xikolo.xcdatamodeld/xikolo.xcdatamodel/contents, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/NewsArticleViewController.swift, xikolo-ios/NewsTableViewCell.swift, xikolo-ios/NewsTableViewController.swift, xikolo-ios/NewsViewController.swift, xikolo-ios/TabNews.storyboard
=> News model

xikolo-common/Data/Helper/CoreDataHelper.swift, xikolo-common/Data/Helper/UserProfileHelper.swift
This adds methods to the CoreDataHelper to remove entities from CoreData.
=> Clear CoreData when user logs out

xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Layouts/Base.lproj/Main.storyboard, xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift
such as using course tab for launch and adding a working segmented control for all/my courses
=> Course list optimizations

xikolo-common/Data/Helper/SpineModelHelper.swift, xikolo-common/Data/Model/NewsArticle+CoreDataProperties.swift, xikolo-common/Data/Model/NewsArticle.swift, xikolo-common/Data/xikolo.xcdatamodeld/xikolo.xcdatamodel/contents, xikolo-ios/AppDelegate.swift, xikolo-ios/Layouts/Base.lproj/TabNews.storyboard, xikolo-ios/ViewControllers/News/NewsArticleViewController.swift, xikolo-ios/ViewControllers/News/NewsTableViewController.swift, xikolo-ios/Views/NewsArticleCell.swift
Added a date to detail view. Markdown is also rendered correctly.
=> Fixed news

xikolo-common/Data/Model/CourseItem+CoreDataProperties.swift, xikolo-common/Data/Model/CourseItem.swift, xikolo-common/Data/xikolo.xcdatamodeld/xikolo.xcdatamodel/contents, xikolo-ios/Views/CourseItemCell.swift
This is still read-only, still waiting for PATCH-Route of APIv2.
=> Added read state to course items

xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard
The navigation bar was covering some content at the top.
=> Fixed insets of quiz web view controller

Podfile, Podfile.lock, xikolo-common/Data/Model/Course+CoreDataProperties.swift, xikolo-common/Data/Model/Course.swift, xikolo-common/Data/xikolo.xcdatamodeld/xikolo.xcdatamodel/contents, xikolo-ios.xcodeproj/project.pbxproj
* Adapted model to fit new accessible attribute. Also renamed open to enroll able.
* Update to cocoa pods 1.1.1 resulted in a pod file configuration change.
=> Api changes & podfile update

xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-common/Data/Model/Course.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Categories/UITableViewCell+enable.swift, xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard, xikolo-ios/Layouts/de.lproj/TabCourses.strings, xikolo-ios/ViewControllers/Courses/CourseDecisionViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Courses/DropdownTableViewController.swift, xikolo-ios/ViewControllers/Courses/DropdownViewController.swift, xikolo-tvos/ViewControllers/CourseDetailsViewController.swift
Fixes #29. The app now shows the course detail page if user is not enrolled. Upcoming course content can't be opened as well. In the future, the `accessible` attribute will be delivered via API.
=> Course details logic

xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard, xikolo-ios/ViewControllers/Courses/CourseDecisionViewController.swift, xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift
Looks like this now on an iPhone 5:
=> Add native course details page. Closes #135

xikolo-ios/Base.lproj/LaunchScreen.storyboard
Originally done by @jprberlin.
=> Updated copyright year

.travis.yml, xikolo-ios.xcodeproj/project.pbxproj
Also fixes the openWHO-iOS target.
Originally done by @rhlff.
=> Added OpenWHO to Travis

xikolo-common/Branding/openHPI/Brand.swift
Originally done by @jprberlin.
=> Removed staging

xikolo-ios/Layouts/Base.lproj/TabDashboard.storyboard, xikolo-ios/ViewControllers/Dashboard/DashboardViewController.swift
Prepare app for release; shake to give feedback is still working though.
=> Remove feedback button

xikolo-common/Data/Model/CourseSection.swift, xikolo-ios/ViewControllers/Courses/CourseContentTableViewController.swift
- Use transient property for sectionNameKeyPath
@bjrne 
Fix for #112 ?
=> Fix section titles of item list view.

xikolo-common/Data/Helper/CourseHelper.swift, xikolo-common/Data/Model/Course.swift, xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Branding/openHPI/Base.lproj/LaunchScreen.storyboard, xikolo-ios/Branding/openSAP/Base.lproj/LaunchScreen.storyboard, xikolo-ios/Branding/openWHO/Base.lproj/LaunchScreen.storyboard, xikolo-ios/Categories/UIApplication+VersionInfo.swift, xikolo-ios/Layouts/Base.lproj/TabProfile.storyboard, xikolo-ios/ViewControllers/Profile/ProfileViewController.swift, xikolo-ios/de.lproj/LaunchScreen.strings, xikolo-ios/de.lproj/Localizable.strings
=> Visual build number, correct copyright, sections in my courses

xikolo-common/Data/Model/Course+CoreDataProperties.swift, xikolo-common/Data/Model/Course.swift, xikolo-common/Data/Model/CourseCertificates.swift, xikolo-common/Data/Model/CourseCertificatesHash.swift, xikolo-common/Data/Model/CourseItem+CoreDataProperties.swift, xikolo-common/Data/Model/CourseItem.swift, xikolo-common/Data/Model/Enrollment+CoreDataProperties.swift, xikolo-common/Data/Model/Enrollment.swift, xikolo-common/Data/Model/EnrollmentCertificates.swift, xikolo-common/Data/xikolo.xcdatamodeld/xikolo 2.xcdatamodel/contents, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/ViewControllers/Courses/CourseContentTableViewController.swift, xikolo-ios/de.lproj/Localizable.strings
Since I am not enrolled in any proctoring courses on a live platform, I couldn't test this. The dialog descriptions still need the correct texts and a translation. Does this warning already exist somewhere else?
=> Support proctored flag

xikolo-ios/ViewControllers/Courses/CourseContentTableViewController.swift, xikolo-ios/ViewControllers/Courses/CourseDecisionViewController.swift, xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Courses/DropdownTableViewController.swift, xikolo-ios/ViewControllers/Courses/DropdownViewController.swift
This reverts commit e37cb71fd359bce27cf2d75fe2e85faefb10d18a.
=> Revert "Make source of course variable clear"

xikolo-ios/AppDelegate.swift
Still needs to be tested on a physical device
=> Add universal link handling for courses, news and dashboard

xikolo-common/Categories/String+regex.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Courses/RichtextViewController.swift
Richtext view now responds correctly to `/files/uuid` and regular `https://` Links
=> Fix link actions

xikolo-ios/Info.plist, xikolo-ios/ViewControllers/Main/LoginViewController.swift, xikolo-ios/ViewControllers/News/NewsArticleViewController.swift, xikolo-ios/Views/CourseActivityRow.swift
* Use `SFSafariViewController` to open register links and links contained in news-articles
* Make sure some courses are shown in dashboard even when not logged in
=> Open links inApp, Dashboard Fix

xikolo-common/Data/Helper/SpineHelper.swift, xikolo-common/Data/Helper/TrackingHelper.swift, xikolo-common/Data/Helper/UserHelper.swift, xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-common/Data/Model/User+CoreDataProperties.swift, xikolo-common/Data/Model/User.swift, xikolo-common/Data/Model/UserProfile+CoreDataProperties.swift, xikolo-common/Data/Model/UserProfile.swift, xikolo-common/Data/Provider/UserProvider.swift, xikolo-common/Data/Routes.swift, xikolo-common/Data/xikolo.xcdatamodeld/xikolo 3.xcdatamodel/contents, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/ViewControllers/Profile/ProfileViewController.swift, xikolo-tvos/ViewControllers/MainViewController.swift
When this is merged, we are using APIv2 for all communication with the server
=> Add user, user-profile, login apiv2

xikolo-common/Data/Helper/CourseSectionHelper.swift
This needs testing once the most recent openSAP version is rolled out
=> Prevent sections from being shown before they should be

.travis.yml
- tvOS for openWHO
- iOS and tvOS for moocHOUSE
Fixes #217
=> Add missing travis build.

Podfile, Podfile.lock, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard, xikolo-ios/ViewControllers/Courses/VideoViewController.swift, xikolo-ios/Views/VideoPlayerControlView.swift
=> Use new video player.

xikolo-common/Data/Model/Video.swift
=> Show correct video stream.

README.md
Something else that should be in the README?
=> Add preferred code settings to README

xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-common/UserDefaultsKeys.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Layouts/Base.lproj/TabSettings.storyboard, xikolo-ios/Layouts/de.lproj/TabSettings.strings, xikolo-ios/ViewControllers/Courses/CourseContentTableViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Profile/SettingsViewController.swift, xikolo-ios/Views/VideoPlayerControlView.swift
=> Add switch to toggle content preloading.

xikolo-common/Data/Helper/SpineHelper.swift, xikolo-ios.xcodeproj/xcshareddata/xcschemes/moocHOUSE-iOS.xcscheme, xikolo-ios.xcodeproj/xcshareddata/xcschemes/moocHOUSE-tvOS.xcscheme, xikolo-ios.xcodeproj/xcshareddata/xcschemes/openHPI-iOS.xcscheme, xikolo-ios.xcodeproj/xcshareddata/xcschemes/openHPI-tvOS.xcscheme, xikolo-ios.xcodeproj/xcshareddata/xcschemes/openSAP-iOS.xcscheme, xikolo-ios.xcodeproj/xcshareddata/xcschemes/openSAP-tvOS.xcscheme, xikolo-ios.xcodeproj/xcshareddata/xcschemes/openWHO-iOS.xcscheme, xikolo-ios.xcodeproj/xcshareddata/xcschemes/openWHO-tvOS.xcscheme
- default: disabled
Fixes #285
=> Add environment variabel to disable Spine logging.

xikolo-common/Branding/moocHOUSE/Brand.swift, xikolo-common/Branding/openHPI/Brand.swift, xikolo-common/Branding/openSAP/Brand.swift, xikolo-common/Branding/openWHO/Brand.swift, xikolo-ios/Layouts/Base.lproj/TabSettings.storyboard, xikolo-ios/ViewControllers/Profile/SettingsViewController.swift
=> Add button to send feedback via email.

xikolo-common/Branding/moocHOUSE/Brand.swift, xikolo-common/Branding/openHPI/Brand.swift, xikolo-common/Branding/openSAP/Brand.swift, xikolo-common/Branding/openWHO/Brand.swift
=> Change to new feedback mail address.

xikolo-ios/ViewControllers/Courses/VideoViewController.swift, xikolo-ios/Views/VideoPlayerControlView.swift
=> Fix full screen mode on iPad.

xikolo-ios/Base.lproj/Localizable.strings, xikolo-ios/Data/Model/Video+DetailedContent.swift, xikolo-ios/Layouts/de.lproj/TabDashboard.strings, xikolo-ios/Layouts/de.lproj/TabSettings.strings, xikolo-ios/de.lproj/Localizable.strings
=> Add localization for missing strings.

xikolo-common/Categories/String+ascii.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Helpers/VideoPersistenceManager.swift
=> Remove invalid characters from video download titles.

xikolo-common/Data/Helper/NetworkHelper.swift, xikolo-ios/Helpers/VideoPersistenceManager.swift
- Since this is now handled by the server.
=> Remove redirect resolver for video download.

xikolo-common/CustomUserDefaults.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Helpers/VideoPersistenceManager.swift, xikolo-ios/Layouts/Base.lproj/TabSettings.storyboard, xikolo-ios/Layouts/de.lproj/TabSettings.strings, xikolo-ios/ViewControllers/Profile/VideoQualityViewController.swift, xikolo-ios/de.lproj/Localizable.strings
=> Add setting option for video download quality.

xikolo-common/Branding/Brand+generic.swift, xikolo-ios/Categories/UIApplication+VersionInfo.swift, xikolo-ios/Layouts/Base.lproj/TabSettings.storyboard, xikolo-ios/ViewControllers/Profile/SettingsViewController.swift, xikolo-ios/de.lproj/Localizable.strings
=> Add link to GitHub repo.

xikolo-ios/Layouts/Base.lproj/TabSettings.storyboard, xikolo-ios/Layouts/de.lproj/TabSettings.strings
see https://stackoverflow.com/a/31874374/7414898
=> Fix layout of preload content setting cell.

xikolo-common/Categories/UIApplication+DeviceInfo.swift, xikolo-common/Data/Helper/TrackingHelper.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/ViewControllers/Profile/SettingsViewController.swift
=> Add system information to feedback mail.

xikolo-ios.xcodeproj/project.pbxproj
Fixes #281 
@bjrne Please, also test all builds for the simulator and on a real device
=> Switch to automatic code signing.

xikolo-ios/ViewControllers/Courses/VideoViewController.swift, xikolo-ios/Views/VideoPlayerControlView.swift
- Refine user interface.
- Fix iPhone landscape mode.
Fixes #197
=> Add label for offline state to video player.

.gitignore, README.md, fastlane/.env, fastlane/.env.moochouse, fastlane/.env.openhpi, fastlane/.env.opensap, fastlane/.env.openwho, fastlane/Appfile, fastlane/Appfile.dummy, fastlane/Fastfile, fastlane/README.md
=> Add fastlane to development toolchain.

xikolo-common/ViewHelpers/Settings.swift, xikolo-ios/AppDelegate.swift
=> Remove deprecated opeURL calls

xikolo-ios/ViewControllers/Courses/WebViewController.swift
=> Fix quiz submission via webview.

xikolo-common/Data/Helper/CourseHelper.swift, xikolo-common/ViewControllers/AbstractCourseListViewController.swift
=> Split user's current course section into active and self-paced courses.

xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-ios/ViewControllers/Courses/WebViewController.swift, xikolo-ios/ViewControllers/Main/LoginViewController.swift
- Send notification for login state change.
- Correct handling of network indicator animation. It would spin indefinitely.
Fixes #344
=> Fix sso login. Reset cookie for sso for openSAP.

xikolo-common/Data/Helper/CoreDataHelper.swift, xikolo-common/Data/Helper/CourseDateHelper.swift, xikolo-common/Data/Helper/PlatformEventHelper.swift, xikolo-common/Data/Helper/SpineHelper.swift, xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-common/ViewHelpers/CollectionViewResultsControllerDelegateImplementation.swift, xikolo-common/ViewHelpers/TableViewResultsControllerDelegateImplementation.swift, xikolo-ios/ViewControllers/Courses/CourseContentTableViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseActivityViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseDatesTableViewController.swift, xikolo-ios/ViewControllers/News/AnnouncementsTableViewController.swift, xikolo-ios/ViewControllers/News/NewsViewController.swift, xikolo-ios/ViewControllers/News/PlatformEventsTableViewController.swift, xikolo-ios/ViewControllers/Profile/SettingsViewController.swift
- Correctly delete all entities.
- Re-fetch relevant content.
- Improve empty state messages.
- Small refactoring.
Fixes #345 
Fixes #347 
Fixes #204
=> Fix login logout transition.

xikolo-ios/Branding/moocHOUSE/Info.plist, xikolo-ios/Branding/openHPI/Info.plist, xikolo-ios/Branding/openSAP/Info.plist, xikolo-ios/Branding/openWHO/Info.plist, xikolo-tvos/Info.plist
Closes #6 and its duplicate #284.
=> Remove NSAllowsArbitraryLoads flag in all apps

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md
- Add code of conduct.
fixes #357
=> Add templates for github issues and pull requests.

xikolo-common/NotificationKeys.swift
=> Align notification keys

xikolo-common/UserDefaultsKeys.swift, xikolo-ios/Layouts/Base.lproj/Main.storyboard, xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift
=> Remove WHO welcome screen

xikolo-ios/Layouts/Base.lproj/TabNews.storyboard
=> Change icon fill strategy, add default icon for better preview

Podfile, Podfile.lock, fastlane/Fastfile, xikolo-common/Data/Model/Course.swift, xikolo-ios/Layouts/de.lproj/TabCourses.strings
Fixes #358
- Use custom version of BartyCrouch.
- Run install command manually.
=> Fix localization check.

xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-common/ViewHelpers/CollectionViewResultsControllerDelegateImplementation.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift
Fixes #382
- line https://github.com/openHPI/xikolo-ios/compare/382-fix-core-data-problem?expand=1#diff-7e45efbf462327197e032ed17253b4ddR70 and the next one add an additonal check for reloading the collection view
- the rest is refactoring (I thought this might influence the error but nope)
=> Prevent Core Data error for course list after login.

xikolo-common/ViewControllers/AbstractCourseListViewController.swift
Fixes Bug found while testing
Init course list with courses when user is logged in
=> Fix load of course list after app start (when logged in)

xikolo-common/Data/Routes.swift
Forces in_app mode for register view
=> fix in app mode for register view

xikolo-common/Data/Helper/TrackingHelper.swift
Fixes #319
- Revise naming
- Add window size
- Add client id.
=> Update default context of analytics events.

xikolo-common/Data/Helper/UserHelper.swift, xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-common/Data/Model/UserProfile.swift, xikolo-ios/Layouts/Base.lproj/TabSettings.storyboard, xikolo-ios/ViewControllers/Profile/SettingsViewController.swift
=> Fix displaying user data in settings tab.

xikolo-common/ViewControllers/AbstractLoginViewController.swift, xikolo-ios/Layouts/Base.lproj/Main.storyboard, xikolo-ios/ViewControllers/Main/LoginViewController.swift
- Highlight register button.
- Round corners for buttons.
- Set tint color for control in register view.
- Refactorings.
Fixes #396 
Fixes #386 
Fixes #266
=> Improve login view.

xikolo-common/Categories/DispatchTimeInterval+DispatchTime.swift, xikolo-common/Categories/Int+DispatchTime.swift, xikolo-common/Categories/Int+DispatchTimeInterval.swift, xikolo-common/Categories/UIRefreshControl.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Layouts/Base.lproj/TabDashboard.storyboard, xikolo-ios/ViewControllers/Courses/CourseContentTableViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseActivityViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseDatesTableViewController.swift, xikolo-ios/ViewControllers/News/AnnouncementsTableViewController.swift, xikolo-ios/ViewControllers/News/PlatformEventsTableViewController.swift
Fixes #365
Add pull to refresh to the following views:
- CourseDatesVC (incl. CourseActivityVC)
- CourseListVC
- CourseContentVC
- AnnouncmentVC
- PlatformEventVC
=> Add pull to refresh to list views

xikolo-ios/Layouts/Base.lproj/Main.storyboard, xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard, xikolo-ios/Layouts/Base.lproj/TabDashboard.storyboard, xikolo-ios/Layouts/Base.lproj/TabNews.storyboard, xikolo-ios/Layouts/Base.lproj/TabSettings.storyboard, xikolo-ios/Layouts/CourseDateHeader.xib
=> Use safe ares in storyboards.

xikolo-ios/Branding/moocHOUSE/Base.lproj/LaunchScreen.storyboard, xikolo-ios/Branding/openHPI/Base.lproj/LaunchScreen.storyboard, xikolo-ios/Branding/openSAP/Base.lproj/LaunchScreen.storyboard, xikolo-ios/Branding/openWHO/Base.lproj/LaunchScreen.storyboard, xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard, xikolo-ios/Layouts/Base.lproj/TabNews.storyboard, xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Courses/RichtextViewController.swift, xikolo-ios/ViewControllers/Courses/VideoViewController.swift, xikolo-ios/ViewControllers/News/AnnouncementViewController.swift
Fixes #402
- make the following views respect the device's safe area:
- lauch screens
- course list
- course detail view
- rich text view 
- announcement view
- hide home indicator when playing videos in landscape orientation.
=> Adjust design for iPhone X

xikolo-common/Data/Helper/CoreDataHelper.swift, xikolo-common/Data/Helper/CourseHelper.swift, xikolo-common/Data/Model/BaseModel.swift, xikolo-ios/ViewControllers/Courses/CourseContentTableViewController.swift, xikolo-ios/ViewControllers/Courses/CourseDecisionViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseActivityViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseDatesTableViewController.swift, xikolo-ios/ViewControllers/News/AnnouncementViewController.swift, xikolo-ios/ViewControllers/News/AnnouncementsTableViewController.swift, xikolo-ios/ViewControllers/News/PlatformEventsTableViewController.swift, xikolo-tvos/AppDelegate.swift
Fixes #404
- Correct displaying data
- Switch to list views if a detail view is displayed on logout
- Course Content -> Coruse list
- Announcement Detail -> Announcement list
=> Improve Core Data operations on logout

xikolo-ios/Layouts/Base.lproj/TabCourses.storyboard
=> Correct order the course labels in course detail view.

xikolo-ios/Views/CourseItemCell.swift
Fixes #417
- Course items are no longer selectable in offline mode.
=> Improve offline state of course items.

xikolo-ios/Base.lproj/Localizable.strings, xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift, xikolo-ios/de.lproj/Localizable.strings
Fixes #387 
Create course enrollment without show an alert asking if the user is sure about this.
=> Fix issue #387 not to show alert when the user enrolls in a course

xikolo-common/Data/Model/Enrollment.swift
Fixes #423
- The API requires a non-optional value for the completed state.
=> Fix course enrollment.

xikolo-common/Data/Routes.swift, xikolo-ios/Layouts/Base.lproj/Main.storyboard, xikolo-ios/Layouts/de.lproj/Main.strings, xikolo-ios/ViewControllers/Main/LoginViewController.swift
Fixes #429
- reset form is shown in web view
=> Add button to reset user password

xikolo-ios/AppDelegate.swift
- If the user is not logged in, the courses tab will be shown.
Fixes #444
=> Show dashboard on app start if the user is logged in.

xikolo-common/Branding/Brand+generic.swift, xikolo-common/Categories/CALayer+UIColor.swift, xikolo-common/Categories/Optional+require.swift, xikolo-common/Categories/SafeCastable.swift, xikolo-common/Data/Helper/NetworkHelper.swift, xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-common/Data/Model/Announcement.swift, xikolo-common/Data/Model/Enrollment.swift, xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-common/ViewHelpers/CollectionViewResultsControllerDelegateImplementation.swift, xikolo-common/ViewHelpers/TableViewResultsControllerDelegateImplementation.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/AppDelegate.swift, xikolo-ios/Categories/UIApplication+AppInfo.swift, xikolo-ios/ViewControllers/Courses/CourseDecisionViewController.swift, xikolo-ios/ViewControllers/Courses/CourseItemListViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Courses/DropdownViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseActivityViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseDatesTableViewController.swift, xikolo-ios/ViewControllers/Login/LoginViewController.swift, xikolo-ios/ViewControllers/News/AnnouncementsTableViewController.swift, xikolo-ios/Views/CenterCellCollectionViewFlowLayout.swift
=> Add require methods to avoid force unwraps.

xikolo-common/Base.lproj/Common.stringsdict, xikolo-common/Data/Helper/FetchRequests/CourseHelper+FetchRequests.swift, xikolo-common/Stroyboard/EmptyCollectionViewCell.xib, xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-common/ViewHelpers/CollectionViewResultsControllerDelegateImplementation.swift, xikolo-common/Views/EmptyCollectionViewCell.swift, xikolo-common/de.lproj/Common.stringsdict, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/Layouts/CourseListLayout.swift, xikolo-ios/NavigationBar+Layout.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/Views/CourseHeaderView.swift
=> Add search to course list

xikolo-ios/ViewControllers/Courses/VideoViewController.swift
=> Disable open slides button in offline mode

xikolo-common/Branding/openSAP/Brand.swift, xikolo-common/Branding/openWHO/Brand.swift, xikolo-common/Data/Helper/AnnouncementHelper.swift, xikolo-common/Data/Helper/CourseDateHelper.swift, xikolo-common/Data/Helper/CourseHelper.swift, xikolo-common/Data/Helper/CourseItemHelper.swift, xikolo-common/Data/Helper/EnrollmentHelper.swift, xikolo-common/Data/Helper/LTIExerciseHelper.swift, xikolo-common/Data/Helper/PeerAssessmentHelper.swift, xikolo-common/Data/Helper/PlatformEventHelper.swift, xikolo-common/Data/Helper/QuizHelper.swift, xikolo-common/Data/Helper/RichTextHelper.swift, xikolo-common/Data/Helper/UserHelper.swift, xikolo-common/Data/Helper/VideoHelper.swift
=> Add discardableResult to methods

xikolo-common/Data/Helper/FetchRequests/CourseHelper+FetchRequests.swift, xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-ios/Base.lproj/Localizable.strings, xikolo-ios/ViewControllers/Dashboard/CourseActivityViewController.swift, xikolo-ios/Views/CourseCell.swift, xikolo-ios/de.lproj/Localizable.strings
- All enrolled courses are shown in the dashboard tab, whether completed or not.
- Course search only list accessible courses.
@bjrne Please test this with your account and check if you can find "spielend Programmieren lernen 2014"
=> Fix showing completed courses

.travis.yml
=> Use stable version of Xcode 9.3 on travis

Podfile.lock, xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-ios/AppDelegate.swift
=> Show alert for openSAP birthday voucher

xikolo-common/Data/Helper/AnnouncementHelper.swift, xikolo-common/Data/Helper/NetworkHelper.swift, xikolo-common/Data/Helper/UserProfileHelper.swift, xikolo-ios/AppDelegate.swift, xikolo-ios/ViewControllers/Account/AccountViewController.swift, xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift, xikolo-ios/ViewControllers/Courses/CourseItemListViewController.swift, xikolo-ios/ViewControllers/Courses/WebViewController.swift, xikolo-ios/Views/AnnouncementCell.swift, xikolo-tvos/ViewControllers/CourseDetailsViewController.swift, xikolo-tvos/ViewControllers/LearningsViewController.swift, xikolo-tvos/ViewControllers/MainViewController.swift
Fixes #268
Implement `isLoggedIn()` as a computed property instead of a method.
=> Make isLoggedIn() a computed property

.gitignore, .swiftlint.yml, Podfile, Podfile.lock, xikolo-common/ViewControllers/AbstractCourseListViewController.swift, xikolo-common/ViewHelpers/CollectionViewResultsControllerDelegateImplementation.swift, xikolo-ios.xcodeproj/project.pbxproj, xikolo-ios/.rswiftignore, xikolo-ios/AppDelegate.swift, xikolo-ios/AppNavigator.swift, xikolo-ios/Data/Model/CouseContent+image.swift, xikolo-ios/Protocols/CourseContentViewController.swift, xikolo-ios/Storyboards/Base.lproj/Course.storyboard, xikolo-ios/ViewControllers/Account/AccountViewController.swift, xikolo-ios/ViewControllers/Courses/CertificatesListViewController.swift, xikolo-ios/ViewControllers/Courses/CourseContent.swift, xikolo-ios/ViewControllers/Courses/CourseContentListViewController.swift, xikolo-ios/ViewControllers/Courses/CourseDetailViewController.swift, xikolo-ios/ViewControllers/Courses/CourseItemListViewController.swift, xikolo-ios/ViewControllers/Courses/CourseListViewController.swift, xikolo-ios/ViewControllers/Courses/RichtextViewController.swift, xikolo-ios/ViewControllers/Courses/VideoViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseActivityViewController.swift, xikolo-ios/ViewControllers/Dashboard/CourseDatesListViewController.swift, xikolo-ios/ViewControllers/Login/LoginViewController.swift, xikolo-ios/ViewControllers/News/AnnouncementsListViewController.swift, xikolo-ios/Views/CourseItemCell.swift, xikolo-ios/Views/CourseItemDetailView.swift
Add R.swift to avoid magic strings (storyboard, asset catalog) and add compile time checks
=> Use R.swift

xikolo-ios/Data/Model/Video+DetailedCourseItem.swift, xikolo-ios/Helpers/PersistenceManager/PersistenceManager.swift, xikolo-ios/Protocols/DetailedCourseItem.swift, xikolo-ios/Storyboards/Base.lproj/CourseLearnings.storyboard, xikolo-ios/Views/CourseItemCell.swift, xikolo-ios/Views/CourseItemDetailView.swift
- Show download progress for stream and video downloads
=> Show download progress next to detailed text

xikolo-common/Data/Helper/TrackingHelper.swift, xikolo-ios/Helpers/PersistenceManager/PersistenceManager.swift, xikolo-ios/Helpers/PersistenceManager/SlidesPersistenceManager.swift, xikolo-ios/Helpers/PersistenceManager/StreamPersistenceManager.swift
- add tracking for slide downloads
- add course and section id to tracking context
=> Track slide downloads

xikolo-common/Base.lproj/Common.strings, xikolo-common/Base.lproj/Common.stringsdict, xikolo-common/Data/Model/Course.swift, xikolo-common/de.lproj/Common.strings, xikolo-common/de.lproj/Common.stringsdict
=> Move localization for certificate explanations

xikolo-ios/Base.lproj/Localizable.strings, xikolo-ios/Storyboards/Base.lproj/CourseDateHeader.xib, xikolo-ios/Storyboards/Base.lproj/TabDashboard.storyboard, xikolo-ios/Storyboards/de.lproj/CourseDateHeader.strings, xikolo-ios/Views/CourseDateCell.swift, xikolo-ios/de.lproj/Localizable.strings
Fixes #522
- Change localization to be similar to web app
- Add time zone to date
=> Rework layout for course date list

iOS/AppDelegate.swift, iOS/Data/CoreDataHelper.swift, iOS/Extensions/UserDefaults/UserDefaults+coreDataModelToCommon.swift, xikolo-ios.xcodeproj/project.pbxproj
- Reset transformable attributes with nested models
- Fixes migration of core data model to common framework
=> Reset transformable attributes with nested models 

iOS/AppDelegate.swift, iOS/Data/CoreDataHelper.swift, iOS/Extensions/UserDefaults/UserDefaults+coreDataModelToCommon.swift, xikolo-ios.xcodeproj/project.pbxproj
- Reset transformable attributes with nested models
- Fixes migration of core data model to common framework
=> Reset transformable attributes with nested models

Common-Tests/BrightFutureTests.swift, xikolo-ios.xcodeproj/project.pbxproj
=> Add tests for BrightFuture extension

Common/Data/Helper/CourseSectionHelper.swift, Common/Data/Helper/FetchRequests/CourseSectionHelper+FetchRequests.swift, Common/Extensions/Date.swift, iOS/Base.lproj/Localizable.strings, iOS/Storyboards/Base.lproj/CourseLearnings.storyboard, iOS/ViewControllers/Courses/CourseItemListViewController.swift, iOS/de.lproj/Localizable.strings
=> Show start date of next section in footer of course item list

Common/Data/Helper/CoreDataHelper.swift, Common/Data/Helper/Sync/SyncPushEngine.swift, Common/Data/Helper/TrackingHelper.swift, Common/Extensions/NSManagedObjectContext+typed.swift, Common/Extensions/Optional+require.swift, Common/Logger.swift, Common/Utilities/SafeCastable.swift, Podfile, Podfile.lock, iOS/AppDelegate.swift, iOS/Helpers/SpotlightHelper.swift, iOS/Settings.bundle/PodLicenses.plist, iOS/ViewControllers/CoreDataCollectionViewDataSource.swift, iOS/ViewControllers/CoreDataTableViewDataSource.swift, iOS/ViewControllers/Courses/PDFWebViewController.swift, iOS/XikoloTabBarController.swift, xikolo-ios.xcodeproj/project.pbxproj
Change logging system to Apple's OSLog
=> Remove XCLogger + use OSLog

iOS/Base.lproj/Localizable.strings, iOS/Storyboards/Base.lproj/TabAccount.storyboard, iOS/Storyboards/de.lproj/TabAccount.strings, iOS/ViewControllers/Account/AccountViewController.swift, iOS/ViewControllers/Account/AccountViewControllerDataSource.swift, iOS/ViewControllers/Account/DownloadSettingsViewController.swift, iOS/ViewControllers/Account/VideoStreamingSettingsViewController.swift, iOS/de.lproj/Localizable.strings, xikolo-ios.xcodeproj/project.pbxproj
Fixes #619
Fixes #341 
- Use separate table view data source for account view controller
=> Make account view controller dynamic

Common/Base.lproj/Localizable.strings, Common/Branding/Brand.swift, Common/Branding/CourseClassifierSearchFilter.swift, Common/Data/Helper/FetchRequests/CourseHelper+FetchRequests.swift, Common/Data/Model/Course.swift, Common/Data/xikolo.xcdatamodeld/xikolo 8.xcdatamodel/contents, Common/de.lproj/Localizable.strings, iOS/Base.lproj/Localizable.strings, iOS/Branding/openHPI/assets-ios-brand.xcassets/BrandConfiguration.dataset/BrandConfiguration.plist, iOS/Branding/openSAP/assets-ios-brand.xcassets/BrandConfiguration.dataset/BrandConfiguration.plist, iOS/Branding/openWHO/assets-ios-brand.xcassets/BrandConfiguration.dataset/BrandConfiguration.plist, iOS/Layouts/CardListLayout.swift, iOS/Storyboards/CourseSearchFilterCell.xib, iOS/ViewControllers/Account/DownloadedContentListViewController.swift, iOS/ViewControllers/Account/DownloadedContentTypeListViewController.swift, iOS/ViewControllers/CoreDataCollectionViewDataSource.swift, iOS/ViewControllers/Courses/CourseListViewController.swift, iOS/ViewControllers/Courses/CourseSearchFilter.swift, iOS/ViewControllers/Courses/CourseSearchFilterOptionsViewController.swift, iOS/ViewControllers/Courses/CourseSearchFiltersViewController.swift, iOS/Views/CourseSearchFilterCell.swift, iOS/Views/DefaultTableViewCell.swift, iOS/de.lproj/Localizable.strings, xikolo-ios.xcodeproj/project.pbxproj
Fixes #593 
Fixes #594
- Add extensible structure for course search filter
- Synchronize course categories and topics
- Accessible when search controller is active
- Add language filter
- Add category filter (enabled via brand config)
- Add topic filter (enabled via brand config)
- Provide clear button to reset filters
=> Course search filters

.travis.yml, README.md, iOS/Extensions/CALayer+roundedCorners.swift, iOS/Storyboards/Base.lproj/CourseLearnings.storyboard, iOS/Storyboards/Base.lproj/Login.storyboard, iOS/Storyboards/Base.lproj/TabAccount.storyboard, iOS/Storyboards/CourseDetails.storyboard, iOS/ViewControllers/Account/DownloadedContentTypeListViewController.swift, iOS/ViewControllers/Courses/CourseDetailViewController.swift, iOS/ViewControllers/Courses/CourseSearchFilterOptionsViewController.swift, iOS/ViewControllers/Courses/CourseSearchFiltersViewController.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/ViewControllers/Courses/LTIHintViewController.swift, iOS/ViewControllers/Courses/VideoViewController.swift, iOS/ViewControllers/Login/LoginViewController.swift, iOS/Views/CertificateCell.swift, iOS/Views/CourseCell.swift, iOS/Views/CourseDateNextUpView.swift, iOS/Views/CourseDateSummaryView.swift, iOS/Views/CourseSearchFilterCell.swift, iOS/Views/PseudoCourseCell.swift, iOS/Views/ShadowContainerView.swift, xikolo-ios.xcodeproj/project.pbxproj
features and changes for iOS 13
=> Support iOS 13

iOS/CourseNavigationController.swift, iOS/ViewControllers/Courses/CourseViewController.swift
=> Adjust status and navigation bar to course visual

Common/Data/Helper/AnnouncementHelper.swift, Common/Data/Helper/UserProfileHelper.swift, iOS-UITests/Screenshots.swift, iOS/AppDelegate.swift, iOS/ViewControllers/Courses/CourseDetailViewController.swift, iOS/ViewControllers/Courses/CourseListViewController.swift, iOS/ViewControllers/News/AnnouncementListViewController.swift, iOS/ViewControllers/News/AnnouncementViewController.swift
- Remove badge for unread announcements in tab bar
- Make AnnouncementHelper static
=> Remove badge for unread announcements in tab bar

Common/Data/Helper/TrackingHelper.swift, iOS/AppDelegate.swift, iOS/Helpers/PersistenceManager/SlidesPersistenceManager.swift, iOS/Helpers/PersistenceManager/StreamPersistenceManager.swift, iOS/ViewControllers/Courses/CourseItemViewController.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/ViewControllers/Courses/VideoViewController.swift, iOS/ViewControllers/Courses/WebViewController.swift, iOS/ViewControllers/Dashboard/DashboardViewController.swift, iOS/ViewControllers/News/AnnouncementListViewController.swift, iOS/ViewControllers/News/AnnouncementViewController.swift
Fixes #666
- Pass current view controller if existing
- Correct window size on iOS 13
=> Remove singleton implementation from TrackingHelper

iOS/AppDelegate.swift, iOS/SceneDelegate.swift, iOS/ViewControllers/Account/DownloadedContentListViewController.swift, iOS/ViewControllers/Dashboard/DashboardViewController.swift, iOS/ViewControllers/News/AnnouncementListViewController.swift
- Move inital setup work the next cycle on main thread
- Move notification observation to viewdidLoad
=> Optimize app launch

iOS/Protocols/CourseAreaViewController.swift, iOS/ViewControllers/Courses/CertificatesListViewController.swift, iOS/ViewControllers/Courses/CourseDetailViewController.swift, iOS/ViewControllers/Courses/CourseItemListViewController.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/ViewControllers/Courses/DocumentListViewController.swift, iOS/ViewControllers/Courses/WebViewController.swift, iOS/ViewControllers/News/AnnouncementListViewController.swift
=> Snap course card when deceleration ends

Common/Data/Helper/TrackingHelper.swift, iOS/Storyboards/CourseLearningsWeb.storyboard, iOS/Storyboards/PDFWebViewController.storyboard, iOS/Storyboards/WebViewController.storyboard, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/ViewControllers/Courses/PDFWebViewController.swift, iOS/ViewControllers/Courses/WebViewController.swift
=> Use WKWebView instead of UIWebView

.swiftlint.yml, Common/Data/Helper/Sync/SyncPushEngine.swift, Common/Data/Model/QuizQuestion.swift, Common/Data/ModelObserver.swift, Common/Extensions/Notification+CoreData.swift, iOS/ViewControllers/CoreDataTableViewDataSource.swift
- Update SwiftLint
- Fix new linter warnings
=> Update SwiftLint rules

iOS/Base.lproj/Localizable.strings, iOS/VideoPlayer/CustomBMPlayer.swift, iOS/VideoPlayer/MediaSelectionDelegate.swift, iOS/VideoPlayer/MediaSelectionOptionCell.swift, iOS/VideoPlayer/MediaSelectionViewController.swift, iOS/VideoPlayer/VideoPlayerControlView.swift, iOS/ViewControllers/Courses/VideoViewController.swift, iOS/assets-ios.xcassets/video player/Contents.json, iOS/assets-ios.xcassets/video player/options.imageset/Contents.json, iOS/assets-ios.xcassets/video player/options.imageset/ios-options.pdf, iOS/de.lproj/Localizable.strings, xikolo-ios.xcodeproj/project.pbxproj
Fixes #79
- Make use of the audio tracks and subtitle options exposed via the HLS playlist
- Recreate the menu of AVPlayerViewController
=> Subtitles menu

Podfile, Podfile.lock, iOS/Info.plist, iOS/VideoPlayer/CustomBMPlayer.swift, iOS/VideoPlayer/VideoPlayerControlView.swift
=> Add support for PictureInPicture video player

iOS/Helpers/PersistenceManager/PersistenceManager.swift, iOS/Helpers/PersistenceManager/StreamPersistenceManager.swift
=> Download additional media selections when persisting video streams

Podfile, Podfile.lock, iOS/AppDelegate.swift, iOS/Extensions/EmptyState/EmptyState.swift, iOS/Extensions/EmptyState/EmptyStateView.swift, iOS/Extensions/EmptyState/Swizzler.swift, iOS/Extensions/EmptyState/UICollectionView+EmptyState.swift, iOS/Extensions/EmptyState/UITableView+EmptyState.swift, iOS/Settings.bundle/PodLicenses.plist, iOS/VideoPlayer/MediaSelectionViewController.swift, iOS/ViewControllers/Account/AvailableCertificatesListViewController.swift, iOS/ViewControllers/Account/DownloadedContentListViewController.swift, iOS/ViewControllers/Courses/CertificatesListViewController.swift, iOS/ViewControllers/Courses/CourseItemListViewController.swift, iOS/ViewControllers/Courses/DocumentListViewController.swift, iOS/ViewControllers/Dashboard/CourseDateListViewController.swift, iOS/ViewControllers/News/AnnouncementListViewController.swift, xikolo-ios.xcodeproj/project.pbxproj
- Remove `DZNEmptyDataSet` as dependency
- Rebuild minimum functionality
=> Rework empty states for table and collection views

Binge/BingePlayerDelegate.swift, Binge/BingePlayerViewController.swift, iOS/Storyboards/Base.lproj/CourseLearningsVideo.storyboard, iOS/ViewControllers/Courses/VideoViewController.swift
=> Adjust size of video player to ratio of video asset

iOS/ViewControllers/CoreDataCollectionViewDataSource.swift, iOS/ViewControllers/Dashboard/CourseOverviewViewController.swift
Fixes #647
- Remove item limit from CoreDataCollectionViewDataSourceDelegate
- Fetch items manually on CoreData changes
=> Rework data source for course overview list

Common/Helpers/MarkdownHelper.swift, iOS/ViewControllers/Courses/CourseDetailsViewController.swift, iOS/ViewControllers/Courses/LTIHintViewController.swift, iOS/ViewControllers/Courses/RichtextViewController.swift, iOS/ViewControllers/Courses/VideoViewController.swift, iOS/ViewControllers/News/AnnouncementViewController.swift
Especially loading images from the internet would contribute to this.
Fixes #710
=> Avoid frozen UI when loading markdown

iOS/Extensions/Sequence+sort.swift, iOS/ViewControllers/Courses/CourseItemViewController.swift, xikolo-ios.xcodeproj/project.pbxproj
=> Fix position label of a course item in navigation bar

iOS/AppDelegate.swift, iOS/AppNavigator.swift, iOS/SceneDelegate.swift, iOS/ViewControllers/CoreDataTableViewDataSource.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/ViewControllers/Login/LoginViewController.swift
=> Improve universal link handling

iOS/Base.lproj/Localizable.strings, iOS/Storyboards/de.lproj/CourseLearningsPeerAssessment.strings, iOS/Storyboards/de.lproj/TabAccount.strings, iOS/de.lproj/Localizable.strings
=> Ensure consistent use of pronouns in German localization

Common/Data/Helper/FetchRequests/CourseHelper+FetchRequests.swift, Common/Data/Model/Course.swift, Common/Data/xikolo.xcdatamodeld/.xccurrentversion, Common/Data/xikolo.xcdatamodeld/xikolo 11.xcdatamodel/contents, iOS/Base.lproj/Localizable.strings, iOS/ViewControllers/Courses/CourseAreaListViewController.swift, iOS/ViewControllers/Courses/CourseDetailsViewController.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/de.lproj/Localizable.strings, xikolo-ios.xcodeproj/project.pbxproj
- Sync external url for courses
- Hide course area list for external courses
- Open external course when tapping on enroll button (different title)
=> Show external courses

.github/workflows/ci.yml, iOS/Base.lproj/Localizable.strings
=> Fix localization check on Github Actions

iOS/Base.lproj/Localizable.strings, iOS/Helpers/PersistenceManager/DownloadedContentHelper.swift, iOS/ViewControllers/Account/DownloadedContentListViewController.swift, iOS/de.lproj/Localizable.strings
Fixes #750
- Show estimated time effort for downloaded content
- aggregated for each course
=> Show estimated time effort for downloaded content

iOS/Helpers/PersistenceManager/DocumentsPersistenceManager.swift, iOS/Helpers/PersistenceManager/DownloadedContentHelper.swift, iOS/Helpers/PersistenceManager/FilePersistenceManager.swift, iOS/Helpers/PersistenceManager/PersistenceManager.swift, iOS/Helpers/PersistenceManager/SlidesPersistenceManager.swift, iOS/Helpers/PersistenceManager/StreamPersistenceManager.swift, iOS/ViewControllers/Account/DownloadedContentTypeListConfiguraton.swift, iOS/ViewControllers/Account/DownloadedContentTypeListViewController.swift, iOS/ViewControllers/Courses/VideoViewController.swift, iOS/Views/DetailedDataItemView.swift, iOS/Views/DocumentLocalizationCell.swift
from protocol to class with a configuration
=> Refactor persistence managers

iOS/Helpers/PersistenceManager/ContentPersistenceManager.swift, iOS/Helpers/PersistenceManager/DownloadedContentHelper.swift, iOS/ViewControllers/Account/DownloadedContentListViewController.swift, iOS/ViewControllers/Account/DownloadedContentTypeListConfiguration.swift, iOS/ViewControllers/Account/DownloadedContentTypeListViewController.swift, iOS/ViewControllers/CoreDataTableViewDataSource.swift, xikolo-ios.xcodeproj/project.pbxproj
=> Show time effort for downloaded content of a single content type in a course

iOS/ViewControllers/Courses/CourseListViewController.swift
- Use diacritic insensitive lookups for course search
Fixes #594
=> Include course classifiers in course search

TodayExtension/Storyboards/Base.lproj/MainInterface.storyboard, TodayExtension/TodayViewController.swift, iOS/ViewControllers/Dashboard/CourseDateOverviewViewController.swift, iOS/ViewControllers/Dashboard/CourseOverviewViewController.swift, xikolo-ios.xcodeproj/project.pbxproj
=> Show next course date in expanded mode of Today widget

.github/workflows/ci.yml, README.md
=> Use Xcode 11.5

Stockpile/Protocols/JSONAPIPushable.swift, Stockpile/SyncEngine.swift, Stockpile/SynchronizationContext.swift, iOS/ViewControllers/Account/HelpdeskTicketTopicListViewController.swift, iOS/ViewControllers/CoreDataCollectionViewDataSource.swift, iOS/ViewControllers/Courses/CourseArea.swift, iOS/ViewControllers/Courses/CourseSearchFilter.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/XikoloTabBarController.swift
=> Use keypaths instead of closures when possible

iOS/CourseNavigationController.swift, iOS/Storyboards/Base.lproj/Course.storyboard, iOS/Transition/CourseInteractionController.swift, iOS/ViewControllers/Courses/CourseViewController.swift
=> Add ability to pull course card upwards

iOS/CourseNavigationController.swift, iOS/ViewControllers/Courses/CourseViewController.swift
=> Fix animation of course navigation bar

Common/Data/Model/CourseItem.swift, Common/Extensions/CourseItem+URL.swift, iOS/Data/Model/CourseItem+DragItem.swift, iOS/Data/Model/CourseItem+NSItemProviderWriting.swift, iOS/ViewControllers/Courses/CourseItemListViewController.swift, iOS/ViewControllers/Courses/CourseItemViewController.swift, iOS/Views/CourseItemCell.swift, xikolo-ios.xcodeproj/project.pbxproj
Fixes no open Issue
Add Drag & Drop to CourseItemList, add ItemSymbol as DragPreview, Drop into other App serves URL with fancy preview or Title and URL as PlainText
=> Support Drag & Drop CourseItem into other Apps

Binge/BingePlayerDelegate.swift, Binge/BingePlayerViewController.swift, Common/Helpers/NetworkIndicator.swift, iOS/AppDelegate.swift, iOS/ViewControllers/Account/AccountViewController.swift, iOS/ViewControllers/Courses/CourseListViewController.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/ViewControllers/Courses/VideoViewController.swift, iOS/ViewControllers/More/AnnouncementViewController.swift, iOS/Views/CertificateCell.swift
=> iOS 13 deprecations & more

Common/Data/Helper/CoreDataHelper.swift, Common/Data/Model/CourseCertificates.swift, Common/Data/Model/CourseCertificatesHash.swift, Common/Data/Model/EnrollmentCertificates.swift, Common/Data/Model/ExerciseProgress.swift, Common/Data/Model/QuizOption.swift, Common/Data/Model/TrackingEventResource.swift, Common/Data/Model/TrackingEventUser.swift, Common/Data/Model/TrackingEventVerb.swift, Common/Data/Model/VideoStream.swift, Common/Data/Model/VisitProgress.swift, Common/Data/XikoloSecureUnarchiveFromDataTransformer.swift, Common/Data/xikolo.xcdatamodeld/.xccurrentversion, Common/Data/xikolo.xcdatamodeld/xikolo 12.xcdatamodel/contents, Common/Extensions/URL+NSURL.swift, xikolo-ios.xcodeproj/project.pbxproj
=> Use value transformers for transformable Core Data attributes

Binge/BingePlayerViewController.swift, iOS/ViewControllers/Courses/VideoViewController.swift
=> Continue playing audio when application enters background

iOS/AppDelegate.swift, iOS/Helpers/PersistenceManager/FilePersistenceManager.swift, iOS/Helpers/PersistenceManager/StreamPersistenceManager.swift
=> Complete background downloads properly

iOS/ViewControllers/Courses/CourseDetailsViewController.swift, iOS/ViewControllers/Courses/CourseViewController.swift, iOS/ViewControllers/Previews/CoursePreviewViewController.swift, iOS/Views/ChannelCell.swift, iOS/Views/ChannelHeaderView.swift, iOS/Views/CourseCell.swift, iOS/Views/UserProfileCell.swift
=> Add fade animation to course and channel visuals

iOS/ViewControllers/Account/DownloadedContentTypeListViewController.swift, iOS/ViewControllers/CoreDataTableViewDataSource.swift, iOS/ViewControllers/Courses/CourseItemListViewController.swift, iOS/ViewControllers/Courses/CourseProgressViewController.swift, iOS/ViewControllers/Courses/DocumentListViewController.swift, iOS/ViewControllers/Dashboard/CourseDateListViewController.swift, iOS/ViewControllers/More/AnnouncementListViewController.swift
=> Use diffable data source for table views that are backed by CoreData

iOS/Data/Model/Actions/Course+Actions.swift, iOS/Data/Model/Actions/CourseItem+Actions.swift, iOS/Storyboards/Base.lproj/TabAccount.storyboard, iOS/ViewControllers/Account/HelpdeskViewController.swift, iOS/ViewControllers/Courses/CourseItemViewController.swift, iOS/ViewControllers/Courses/CourseViewController.swift
=> Open helpdesk in course context

iOS/Storyboards/Base.lproj/CourseLearnings.storyboard, iOS/ViewControllers/Courses/CourseItemListViewController.swift, iOS/Views/CourseItemCell.swift
=> Scale course item icon and unvisited marker with dynamic text

.github/workflows/ci.yml, README.md
Use Xcode 12 for Github Actions
=> Use Xcode 12

iOS/Storyboards/PDFWebViewController.storyboard, iOS/ViewControllers/Courses/PDFViewController.swift, xikolo-ios.xcodeproj/project.pbxproj
Fixes #539
- Only available on iOS 11 and later
- Use current implementation for iOS 10 (WkWebView)
=> Use PDFKit to display PDFs

iOS/Storyboards/Base.lproj/CourseLearningsLTI.storyboard, iOS/Storyboards/de.lproj/CourseLearningsLTI.strings, iOS/ViewControllers/Courses/LTIExerciseHintViewController.swift
=> Handle missing LTI providers

Common/Helpers/Markdown/AsyncImagesStyler.swift
Closes #808
- Add different styling of HMTL code included in rich text items (font, text color, background color)
=> Improve styling of html in rich text items

Binge/BingeControlDelegate.swift, Binge/BingeControlsViewController.swift, Binge/BingePlayerViewController.swift, Binge/BingeTimeSlider.swift, Common/Data/Helper/VideoHelper.swift, Common/Data/Model/Video.swift, Common/Data/xikolo.xcdatamodeld/xikolo 14.xcdatamodel/contents, fastlane/Snapfile, iOS/Data/Model/CourseItem+DetailedContent.swift, iOS/Data/Model/Video+Preloading.swift, iOS/Extensions/Binge+Video.swift, iOS/Helpers/PersistenceManager/DownloadState.swift, iOS/Protocols/DetailedCourseItemContent.swift, iOS/ViewControllers/Courses/VideoViewController.swift, iOS/Views/CourseItemCell.swift, iOS/Views/DetailedDataItemView.swift
Fixes #565
- Continue video playback on last local position
- Display remaining time in course cell
- Improve appearance of progress slider
- Improve seeking behavior
=> Various improvements to the video player
