xikolo-ios.xcodeproj/project.pbxproj
xikolo-ios/Base.lproj/Main.storyboard
xikolo-ios/Base.lproj/TabCourses.storyboard
xikolo-ios/Base.lproj/TabDashboard.storyboard
xikolo-ios/Base.lproj/TabProfile.storyboard
xikolo-ios/CourseContentTableViewController.swift
xikolo-ios/CourseOverviewViewController.swift
xikolo-ios/DashboardViewController.swift
xikolo-ios/NewsViewController.swift
xikolo-ios/ProfileViewController.swift
xikolo-ios/TabNews.storyboard

Refactored Storyboards to solve some major problems, mainly regarding the title zone in the navigation bar. It also helps preserving states across tabs.
I achieved it by creating a separate NavigationsController as the root ViewController for every tab instead of one as a parent of the TabBarController.

Refactoring ios storyboards

---

Podfile.lock

In 42f9b3b the `Podfile` probably was changed without running `pod install` so the `Podfile.lock` wasn't changed when it should have.

Fix Podfile.lock after pod file change without changing the lock file

---

xikolo-ios/AppDelegate.swift

- Use dummy certificate to prevent cancelation of request.

Fix loading web images on openSAP.

---

xikolo-ios/Helpers/NetworkIndicator.swift

- Allow only positive values for counter.
Fixes #203

Make network indicator helder thread-safe.

---

fastlane/Fastfile

To get a reference of the current version.

Add version number to commit message on build number increment.

---

fastlane/Fastfile
fastlane/README.md
xikolo-ios.xcodeproj/project.pbxproj
xikolo-ios/Branding/moocHOUSE/Info.plist
xikolo-ios/Branding/openHPI/Info.plist
xikolo-ios/Branding/openSAP/Info.plist
xikolo-ios/Branding/openWHO/Info.plist

Fixes #400
- Base build numbers on git history (number of commits)
- Formats:
- master: `[number of commits on master]`
- dev: `[number of commits on master].[number of commits on dev ahead of master]`
- feature: `[number of commits on master].[number of commits on dev ahead of master].0` (leading zero)
- Add fastlane command to find commit for build number (only for build on master or dev)
- Build numbers will not be commited via git (0 as default value)

Handle build numbers automatically

---

xikolo-common/Data/Helper/UserProfileHelper.swift
xikolo-common/Data/Routes.swift

- Temporary workaround before we support APi versioning
- Remove old API v1 routes

Pin server requests to API version 2

---

xikolo-common/Data/Routes.swift
xikolo-ios/Branding/moocHOUSE/Info.plist
xikolo-ios/Branding/openHPI/Info.plist
xikolo-ios/Branding/openSAP/Info.plist
xikolo-ios/Branding/openWHO/Info.plist

We have to release a patch version of the current app which pins the API requests to API version 2 in order to prevent app crashes when API version 3 is released in the next days.

Patch release to pin API version

---

xikolo-ios/AppDelegate.swift
xikolo-ios/Views/VideoPlayerControlView.swift

Fixes #363 
I'm not sure wether this is worth the additional line in the Appdelegate. We could also just delete the line since
* it periodically gets saved by Apple
* we don't need it in another thread and
* if we crash shortly after setting the playback rate I think we have bigger problems than the possibly wrong speed in the next video view. 
At the same time I don't think the performance penalty even justifies thinking about this one line this long ;)

Move synchronize to better place

---

Common/Data/Helper/Sync/SyncEngine.swift
Common/Data/Helper/Sync/SyncPushEngine.swift
Common/Extensions/Future+inject.swift
Common/Helpers/MarkdownHelper.swift
iOS/AppNavigator.swift
iOS/Helpers/PersistenceManager/PersistenceManager.swift
iOS/ViewControllers/Account/AccountViewController.swift

Simplify and improve usage of Result pod

---

Common/Data/Helper/AnnouncementHelper.swift
iOS/Base.lproj/Localizable.strings
iOS/Storyboards/Base.lproj/TabNews.storyboard
iOS/ViewControllers/News/AnnouncementsListViewController.swift
iOS/de.lproj/Localizable.strings

Fixes #90
- Add user action to mark as announcements as read
- Add action menu to announcement list (only visible when logged in)

Add user action to mark as announcements as read

---

iOS/Helpers/PersistenceManager/FilePersistenceManager.swift

by including the course-item content UUID and the download type in the file name. This lead to only the last pdf being available if the file names were the same.
We could also change the filename when sharing the file from the PDFViewController. It currently features the UUID of the item and is pretty long. We could create a hardlink in the temp directory to avoid having to copy the file since there doesn't seem to be a way to rename the file before it is shared.

Fix download names having the same file name

---

Xcode Configurations/moocHOUSE/moocHOUSE-iOS-Debug.xcconfig
Xcode Configurations/openHPI/openHPI-iOS-Debug.xcconfig
Xcode Configurations/openSAP/openSAP-iOS-Debug.xcconfig
Xcode Configurations/openWHO/openWHO-iOS-Debug.xcconfig

- Add compiler flag which create warnings if compile times for functions or expressions exceed the given threshold
- only in debug mode
- current threshold: 150ms
@bjrne please test this on your older machine. I don't want to set the threshold too low

Show warnings for long compile times

---

Common/Data/Model/CourseItem.swift
Common/Data/xikolo.xcdatamodeld/xikolo 9.xcdatamodel/contents
iOS/Data/Model/CourseItem+DetailedContent.swift
iOS/Data/Model/RichText+Preloading.swift
iOS/Data/Model/Video+Preloading.swift
iOS/Protocols/CourseItemCellDelegate.swift
iOS/Protocols/DetailedCourseItemContent.swift
iOS/Protocols/PreloadableCourseItemContent.swift
iOS/Storyboards/Base.lproj/CourseLearnings.storyboard
iOS/ViewControllers/Courses/CourseItemListViewController.swift
iOS/Views/CourseItemCell.swift
iOS/Views/DetailedDataItemView.swift
xikolo-ios.xcodeproj/project.pbxproj

Fixes #729
- Show effort provided by the server for all course items
- By extension, the following change hab to be performed:
- Remove preloading UI (shimmer) for course items
- Split course item protocols for preloading and detailed content
- The `time effort` detailed data replaces `stream` and `text`
- Adjust/Improv storyboard file for course item cell

Show time effort for course items

---

Common/Data/Model/CourseDate.swift
iOS/Storyboards/Base.lproj/CourseDateOverview.storyboard
iOS/Storyboards/Base.lproj/CourseDates.storyboard
iOS/ViewControllers/CoreDataTableViewDataSource.swift
iOS/ViewControllers/Dashboard/CourseDateListViewController.swift
iOS/ViewControllers/Dashboard/CourseDateOverviewViewController.swift
iOS/Views/CourseDateCell.swift

Fixes #745
- iOS 13 only, as `RelativeDateTimeFormatter` is available starting with iOS 13
- show remaining (relative) time up to next deadline in "next up" view on the dashboard (additionally to absolute date)
- Group course date list by relative time

Show relative course dates in course date overview and list

---

iOS/ViewControllers/Courses/CourseDetailsViewController.swift
iOS/ViewControllers/Courses/CourseListViewController.swift
iOS/ViewControllers/Courses/VideoViewController.swift

Fixes #698 
Previously, when users played music in the background while using the app, the music stopped as soon as a video was started but didn't resume, when the video was stopped again. 
Now, I adjusted the AVAudioSession mode so the music played in the background will resume once the video is stopped.

resume background audio when video stops playing

---

.gitignore
Gemfile
Gemfile.lock
fastlane/Fastfile
fastlane/README.md

* Remove strings that are excluded by BartyCrouch via `#bc0ignore!`
* Remove files without localization strings

Add fastlane command to export localization strings

---

Common/Data/RelationshipKeyPath.swift
Common/Data/RelationshipKeyPathsObserver.swift
Common/Data/RichFetchRequest.swift
Common/Extensions/Notification+CoreData.swift
iOS/ViewControllers/Account/DownloadedContentListViewController.swift
iOS/ViewControllers/Courses/CourseListViewController.swift
iOS/ViewControllers/Dashboard/CourseDateOverviewViewController.swift
iOS/ViewControllers/Dashboard/CourseOverviewViewController.swift
iOS/ViewControllers/More/AnnouncementListViewController.swift
xikolo-ios.xcodeproj/project.pbxproj

Fixes #600
When unenrolling from courses without an Internet connection, the object state of the enrollment is set to `deleted`. Only after reconnecting to the Internet, the enrollment object is deleted from the database. In the meantime, the change to the object state attribute is not reflected in the UI as 'NSFetchedResultsController` does not observe changes in related objects. This includes also not being aware of changes to the number the fetched object via the specified search predicate.
In order to fix this, we have to observe all changes to the database and refresh the data manually if necessary. For this, we need the specify the relationship of the object which shall be observed. I adapted the code from [this blog post](https://www.avanderlee.com/swift/nsfetchedresultscontroller-o …

Refresh data when unenrolling from courses 

---

fastlane/Fastfile

In order to avoid doing this manually

Disable IDFA usage in App Store Connect

---

iOS/ViewControllers/Courses/CourseItemWebViewController.swift
iOS/ViewControllers/Courses/WebViewController.swift

Fixes #876
- Fix overlapping content by manipulating the content of the webview
- Inject custom CSS with via JS in the webview
- Improve initialization of webview
- Remove unused code

Avoid next and previous item buttons overlapping with embedded webview content
